name: PR Label and Milestone Check

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check_pr:
    runs-on: smart-contracts-linux-medium

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Check PR labels and milestones
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
        run: node .github/scripts/check-pr.js
