name: Release Production Environment

on:
  push:
    tags: [v*]

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  OWNER: hashgraph
  PACKAGE_NAME: hedera-smart-contracts
  REGISTRY: ghcr.io

jobs:
  npm-package-artifact:
    runs-on: smart-contracts-linux-medium

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: './hedera-smart-contracts'

      - name: Get tag
        run: echo "TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Produce artifact
        run: tar -czf ${{ env.PACKAGE_NAME }}-v${{env.TAG}}.tgz -C ./hedera-smart-contracts .

      - name: Upload artifact
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
        with:
          name: ${{ env.PACKAGE_NAME }}-v${{env.TAG}}
          path: ./*.tgz
          if-no-files-found: error
